"use client";

import { useEffect, useMemo, useState } from "react";
import { Copy, Dumbbell, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Card, CardContent } from "@/components/ui/Card";
import { Input, Label, Textarea } from "@/components/ui/Input";
import { PageHeader } from "@/components/ui/PageHeader";
import { Select } from "@/components/ui/Select";
import { createClient } from "@/lib/supabase/client";

type Paciente={id:string;nome:string|null;email:string|null};
type Treino={id:string;paciente_id:string;nome:string;codigo:string|null;objetivo:string|null;bloco:string|null;ordem:number;status:string;observacoes:string|null};
type Exercicio={id:string;treino_id:string;ordem:number;nome:string;series:number;repeticoes:string|null;rir:string|null;descanso_seg:number|null;video_url:string|null;observacoes:string|null};

export default function TreinosPage(){
 const sb=useMemo(()=>createClient() as any,[]);
 const [pacientes,setPacientes]=useState<Paciente[]>([]),[pacienteId,setPacienteId]=useState("");
 const [treinos,setTreinos]=useState<Treino[]>([]),[exercicios,setExercicios]=useState<Record<string,Exercicio[]>>({});
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showNew,setShowNew]=useState(false);
 const [novo,setNovo]=useState({nome:"",codigo:"",objetivo:"",bloco:"",observacoes:""});
 const [novoEx,setNovoEx]=useState<Record<string,{nome:string;series:string;repeticoes:string;rir:string;descanso:string;video:string;obs:string}>>({});
 const blankEx={nome:"",series:"3",repeticoes:"10",rir:"2",descanso:"60",video:"",obs:""};
 useEffect(()=>{void carregarPacientes()},[]);
 useEffect(()=>{if(pacienteId)void carregarTreinos(pacienteId);else{setTreinos([]);setExercicios({})}},[pacienteId]);
 async function carregarPacientes(){setLoading(true);const r=await sb.from("pacientes").select("id,nome,email").order("nome");setLoading(false);if(r.error)return alert("Não foi possível carregar os pacientes.");const rows=(r.data??[]) as Paciente[];setPacientes(rows);const first=rows[0];if(first)setPacienteId(first.id)}
 async function carregarTreinos(pid:string){setLoading(true);const r=await sb.from("treino_programas").select("*").eq("paciente_id",pid).order("ordem");if(r.error){setLoading(false);return alert("Não foi possível carregar os treinos.")}const rows=(r.data??[]) as Treino[];setTreinos(rows);const ids=rows.map(x=>x.id);if(!ids.length){setExercicios({});setLoading(false);return}const e=await sb.from("treino_exercicios").select("*").in("treino_id",ids).order("ordem");setLoading(false);if(e.error)return alert("Não foi possível carregar os exercícios.");const g:Record<string,Exercicio[]>={};for(const x of (e.data??[]) as Exercicio[])(g[x.treino_id]??=[]).push(x);setExercicios(g)}
 async function criarTreino(){if(!pacienteId||!novo.nome.trim())return;setSaving(true);const r=await sb.from("treino_programas").insert({paciente_id:pacienteId,nome:novo.nome.trim(),codigo:novo.codigo||null,objetivo:novo.objetivo||null,bloco:novo.bloco||null,observacoes:novo.observacoes||null,ordem:treinos.length+1,status:"ativo"});setSaving(false);if(r.error)return alert(r.error.message);setNovo({nome:"",codigo:"",objetivo:"",bloco:"",observacoes:""});setShowNew(false);await carregarTreinos(pacienteId)}
 async function salvarTreino(t:Treino,patch:Partial<Treino>){const r=await sb.from("treino_programas").update(patch).eq("id",t.id);if(r.error)return alert("Não foi possível salvar.");setTreinos(p=>p.map(x=>x.id===t.id?{...x,...patch}:x))}
 async function duplicar(t:Treino){setSaving(true);const n=await sb.from("treino_programas").insert({paciente_id:t.paciente_id,nome:`${t.nome} · Cópia`,codigo:t.codigo,objetivo:t.objetivo,bloco:t.bloco,observacoes:t.observacoes,ordem:treinos.length+1,status:"ativo"}).select("id").single();if(n.error||!n.data){setSaving(false);return alert("Não foi possível duplicar.")}const lista=exercicios[t.id]??[];if(lista.length)await sb.from("treino_exercicios").insert(lista.map((e,i)=>({treino_id:n.data.id,bloco_ordem:1,bloco_nome:"Principal",ordem:i+1,nome:e.nome,series:e.series,repeticoes:e.repeticoes,rir:e.rir,descanso_seg:e.descanso_seg,video_url:e.video_url,observacoes:e.observacoes})));setSaving(false);await carregarTreinos(pacienteId)}
 function formEx(id:string){return novoEx[id]??blankEx}function patchEx(id:string,p:any){setNovoEx(s=>({...s,[id]:{...formEx(id),...p}}))}
 async function adicionarEx(tid:string){const f=formEx(tid);if(!f.nome.trim())return;setSaving(true);const r=await sb.from("treino_exercicios").insert({treino_id:tid,bloco_ordem:1,bloco_nome:"Principal",ordem:(exercicios[tid]?.length??0)+1,nome:f.nome.trim(),series:Number(f.series||1),repeticoes:f.repeticoes||null,rir:f.rir||null,descanso_seg:f.descanso?Number(f.descanso):null,video_url:f.video||null,observacoes:f.obs||null});setSaving(false);if(r.error)return alert(r.error.message);setNovoEx(s=>({...s,[tid]:blankEx}));await carregarTreinos(pacienteId)}
 async function salvarEx(e:Exercicio,patch:Partial<Exercicio>){const r=await sb.from("treino_exercicios").update(patch).eq("id",e.id);if(r.error)return alert("Não foi possível salvar o exercício.");setExercicios(s=>({...s,[e.treino_id]:(s[e.treino_id]??[]).map(x=>x.id===e.id?{...x,...patch}:x)}))}
 async function removerEx(e:Exercicio){if(!confirm(`Remover ${e.nome}?`))return;const r=await sb.from("treino_exercicios").delete().eq("id",e.id);if(r.error)return alert("Não foi possível remover.");setExercicios(s=>({...s,[e.treino_id]:(s[e.treino_id]??[]).filter(x=>x.id!==e.id)}))}
 const ativos=treinos.filter(t=>t.status!=="arquivado");
 return <div><PageHeader title="Treinos" description="Prescrição e gestão dos treinos de cada paciente." actions={<Button onClick={()=>setShowNew(v=>!v)}><Plus className="size-4"/> Novo treino</Button>}/>
 <Card className="mb-5"><CardContent className="pt-6"><Label>Paciente</Label><Select value={pacienteId} onChange={e=>setPacienteId(e.target.value)}><option value="">Selecione...</option>{pacientes.map(p=><option key={p.id} value={p.id}>{p.nome??p.email??"Paciente"}</option>)}</Select><p className="mt-2 text-xs text-muted">{ativos.length} treino(s) ativo(s)</p></CardContent></Card>
 {showNew&&<Card className="mb-5"><CardContent className="pt-6"><h2 className="mb-4 font-bold">Novo treino</h2><div className="grid gap-3 md:grid-cols-2"><div><Label>Nome *</Label><Input value={novo.nome} onChange={e=>setNovo({...novo,nome:e.target.value})} placeholder="Treino A · Inferiores"/></div><div><Label>Código</Label><Input value={novo.codigo} onChange={e=>setNovo({...novo,codigo:e.target.value})}/></div><div><Label>Objetivo</Label><Input value={novo.objetivo} onChange={e=>setNovo({...novo,objetivo:e.target.value})}/></div><div><Label>Bloco</Label><Input value={novo.bloco} onChange={e=>setNovo({...novo,bloco:e.target.value})}/></div></div><div className="mt-3"><Label>Observações</Label><Textarea value={novo.observacoes} onChange={e=>setNovo({...novo,observacoes:e.target.value})}/></div><div className="mt-4 flex justify-end"><Button disabled={saving||!novo.nome.trim()} onClick={()=>void criarTreino()}>{saving?"Salvando...":"Criar treino"}</Button></div></CardContent></Card>}
 {loading?<Card><CardContent className="py-12 text-center text-sm text-muted">Carregando...</CardContent></Card>:<div className="space-y-4">{ativos.map(t=><Card key={t.id}><CardContent className="pt-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 flex-1 items-center gap-2"><Dumbbell className="size-5 shrink-0 text-brand-dark"/><Input className="max-w-xl font-bold" value={t.nome} onChange={e=>setTreinos(s=>s.map(x=>x.id===t.id?{...x,nome:e.target.value}:x))} onBlur={e=>void salvarTreino(t,{nome:e.target.value})}/></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void duplicar(t)}><Copy className="size-4"/> Duplicar</Button><Button variant="outline" onClick={()=>void salvarTreino(t,{status:"arquivado"})}>Arquivar</Button></div></div><p className="mt-2 text-sm text-muted">{t.codigo?`${t.codigo} · `:""}{t.objetivo||"Sem objetivo descrito"}{t.bloco?` · ${t.bloco}`:""}</p>
 <div className="mt-5 space-y-3">{(exercicios[t.id]??[]).map((e,i)=><div key={e.id} className="rounded-xl border border-border bg-bg-alt p-4"><div className="mb-3 flex justify-between gap-2"><strong>{i+1}. {e.nome}</strong><button onClick={()=>void removerEx(e)} className="text-muted hover:text-red-600"><Trash2 className="size-4"/></button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><Label>Exercício</Label><Input value={e.nome} onChange={v=>setExercicios(s=>({...s,[t.id]:(s[t.id]??[]).map(x=>x.id===e.id?{...x,nome:v.target.value}:x)}))} onBlur={v=>void salvarEx(e,{nome:v.target.value})}/></div><div><Label>Séries</Label><Input type="number" defaultValue={e.series} onBlur={v=>void salvarEx(e,{series:Number(v.target.value)})}/></div><div><Label>Repetições</Label><Input defaultValue={e.repeticoes??""} onBlur={v=>void salvarEx(e,{repeticoes:v.target.value||null})}/></div><div><Label>RIR</Label><Input defaultValue={e.rir??""} onBlur={v=>void salvarEx(e,{rir:v.target.value||null})}/></div></div><div className="mt-3 grid gap-3 lg:grid-cols-3"><div><Label>Descanso (s)</Label><Input type="number" defaultValue={e.descanso_seg??""} onBlur={v=>void salvarEx(e,{descanso_seg:v.target.value?Number(v.target.value):null})}/></div><div><Label>Vídeo</Label><Input defaultValue={e.video_url??""} onBlur={v=>void salvarEx(e,{video_url:v.target.value||null})}/></div><div><Label>Orientações</Label><Input defaultValue={e.observacoes??""} onBlur={v=>void salvarEx(e,{observacoes:v.target.value||null})}/></div></div></div>)}</div>
 <div className="mt-4 rounded-xl border border-dashed border-border p-4"><p className="mb-3 text-sm font-semibold">Adicionar exercício</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><div className="lg:col-span-2"><Label>Exercício *</Label><Input value={formEx(t.id).nome} onChange={e=>patchEx(t.id,{nome:e.target.value})}/></div><div><Label>Séries</Label><Input type="number" value={formEx(t.id).series} onChange={e=>patchEx(t.id,{series:e.target.value})}/></div><div><Label>Repetições</Label><Input value={formEx(t.id).repeticoes} onChange={e=>patchEx(t.id,{repeticoes:e.target.value})}/></div><div><Label>RIR</Label><Input value={formEx(t.id).rir} onChange={e=>patchEx(t.id,{rir:e.target.value})}/></div><div><Label>Descanso</Label><Input type="number" value={formEx(t.id).descanso} onChange={e=>patchEx(t.id,{descanso:e.target.value})}/></div></div><div className="mt-3 grid gap-3 lg:grid-cols-2"><Input placeholder="URL do vídeo" value={formEx(t.id).video} onChange={e=>patchEx(t.id,{video:e.target.value})}/><Input placeholder="Orientações" value={formEx(t.id).obs} onChange={e=>patchEx(t.id,{obs:e.target.value})}/></div><div className="mt-3 flex justify-end"><Button disabled={saving||!formEx(t.id).nome.trim()} onClick={()=>void adicionarEx(t.id)}><Plus className="size-4"/> Adicionar exercício</Button></div></div>
 </CardContent></Card>)}{!ativos.length&&pacienteId&&<Card><CardContent className="py-12 text-center text-sm text-muted">Nenhum treino ativo para este paciente.</CardContent></Card>}</div>}</div>
}