"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Copy, Download, Dumbbell, Eye, EyeOff, Library, Plus, Search, Trash2, Users } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Card, CardContent } from "@/components/ui/Card";
import { Input, Label, Textarea } from "@/components/ui/Input";
import { PageHeader } from "@/components/ui/PageHeader";
import { Select } from "@/components/ui/Select";
import { createClient } from "@/lib/supabase/client";

type Paciente={id:string;nome:string|null;email:string|null;treino_liberado:boolean;treino_frequencia_semanal:number|null;status:string|null};
type Treino={id:string;paciente_id:string;nome:string;codigo:string|null;objetivo:string|null;bloco:string|null;ordem:number;status:string;observacoes:string|null;frequencia_semanal:number|null;template_id:string|null};
type Exercicio={id:string;treino_id:string;ordem:number;bloco_ordem:number;bloco_nome:string|null;nome:string;series:number;repeticoes:string|null;rir:string|null;rpe:string|null;descanso_seg:number|null;carga_inicial:number|null;video_url:string|null;observacoes:string|null;exercicio_biblioteca_id:string|null};
type Template={id:string;nome:string;descricao:string|null;objetivo:string|null;categoria:string|null;nivel:string|null;frequencia_semanal:number;duracao_min:number|null;duracao_semanas:number|null;enfase:string|null;modalidade:string|null;bloco:string|null;ativo:boolean;created_at:string};
type TemplateEx={id:string;template_id:string;ordem:number;bloco_ordem:number;bloco_nome:string|null;nome:string;series:number;repeticoes:string|null;rir:string|null;rpe:string|null;descanso_seg:number|null;carga_inicial:number|null;video_url:string|null;observacoes:string|null;exercicio_biblioteca_id:string|null};
type Execucao={id:string;paciente_id:string;treino_id:string;iniciado_em:string;finalizado_em:string|null;duracao_seg:number;concluido:boolean;dados:any};
type Progresso={paciente_id:string;dados:any;updated_at:string};
type View="prescricao"|"biblioteca"|"engajamento";

type AnalyticsRow={
 paciente:Paciente; frequencia:number; semana:number; ultimos28:number; adesao:number; ultimo:string|null; diasSemTreino:number|null; tendencia:number; sessaoAberta:boolean; status:"Alta aderência"|"Atenção"|"Risco"|"Inativo"|"Sem registro";
};

const blankEx={nome:"",series:"3",repeticoes:"10",rir:"2",descanso:"60",video:"",obs:""};
const freqOptions=[1,2,3,4,5,6,7];

function startOfDay(d:Date){const x=new Date(d);x.setHours(0,0,0,0);return x}
function daysBetween(a:Date,b:Date){return Math.floor((startOfDay(a).getTime()-startOfDay(b).getTime())/86400000)}
function fmtDate(value:string|null){if(!value)return "—";return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit"}).format(new Date(value))}
function fmtDuration(sec:number){if(!sec)return "—";const m=Math.round(sec/60);return `${m} min`}
function csvCell(v:unknown){return `"${String(v??"").replaceAll('"','""')}"`}

export default function TreinosPage(){
 const sb=useMemo(()=>createClient() as any,[]);
 const [view,setView]=useState<View>("prescricao");
 const [pacientes,setPacientes]=useState<Paciente[]>([]),[pacienteId,setPacienteId]=useState("");
 const [treinos,setTreinos]=useState<Treino[]>([]),[todosTreinos,setTodosTreinos]=useState<Treino[]>([]),[exercicios,setExercicios]=useState<Record<string,Exercicio[]>>({});
 const [templates,setTemplates]=useState<Template[]>([]),[templateEx,setTemplateEx]=useState<Record<string,TemplateEx[]>>({});
 const [execucoes,setExecucoes]=useState<Execucao[]>([]),[progressos,setProgressos]=useState<Progresso[]>([]);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showNew,setShowNew]=useState(false);
 const [novo,setNovo]=useState({nome:"",codigo:"",objetivo:"",bloco:"",observacoes:"",frequencia:"3"});
 const [novoEx,setNovoEx]=useState<Record<string,typeof blankEx>>({});
 const [buscaTemplate,setBuscaTemplate]=useState(""),[filtroObjetivo,setFiltroObjetivo]=useState(""),[filtroNivel,setFiltroNivel]=useState("");
 const [copySourcePatient,setCopySourcePatient]=useState(""),[copySourceWorkout,setCopySourceWorkout]=useState("");

 useEffect(()=>{void bootstrap()},[]);
 useEffect(()=>{if(pacienteId)void carregarTreinos(pacienteId);else{setTreinos([]);setExercicios({})}},[pacienteId]);

 async function bootstrap(){
  setLoading(true);
  const since=new Date(Date.now()-120*86400000).toISOString();
  const [p,tpl,tplEx,allT,exec,prog]=await Promise.all([
   sb.from("pacientes").select("id,nome,email,treino_liberado,treino_frequencia_semanal,status").order("nome"),
   sb.from("treino_templates").select("*").eq("ativo",true).order("nome"),
   sb.from("treino_template_exercicios").select("*").order("bloco_ordem").order("ordem"),
   sb.from("treino_programas").select("*").order("paciente_id").order("ordem"),
   sb.from("treino_execucoes").select("*").gte("iniciado_em",since).order("iniciado_em",{ascending:false}),
   sb.from("treino_progresso").select("paciente_id,dados,updated_at")
  ]);
  const rows=(p.data??[]) as Paciente[];setPacientes(rows);if(rows[0])setPacienteId(rows[0].id);
  setTemplates((tpl.data??[]) as Template[]);setTodosTreinos((allT.data??[]) as Treino[]);setExecucoes((exec.data??[]) as Execucao[]);setProgressos((prog.data??[]) as Progresso[]);
  const tg:Record<string,TemplateEx[]>={};for(const e of (tplEx.data??[]) as TemplateEx[])(tg[e.template_id]??=[]).push(e);setTemplateEx(tg);
  setLoading(false);
 }

 async function carregarTreinos(pid:string){
  const r=await sb.from("treino_programas").select("*").eq("paciente_id",pid).order("ordem");if(r.error)return alert("Não foi possível carregar os treinos.");
  const rows=(r.data??[]) as Treino[];setTreinos(rows);const ids=rows.map(x=>x.id);if(!ids.length){setExercicios({});return}
  const e=await sb.from("treino_exercicios").select("*").in("treino_id",ids).order("bloco_ordem").order("ordem");if(e.error)return alert("Não foi possível carregar os exercícios.");
  const g:Record<string,Exercicio[]>={};for(const x of (e.data??[]) as Exercicio[])(g[x.treino_id]??=[]).push(x);setExercicios(g);
 }

 async function refreshCore(){await bootstrap();if(pacienteId)await carregarTreinos(pacienteId)}

 async function criarTreino(){if(!pacienteId||!novo.nome.trim())return;setSaving(true);const r=await sb.from("treino_programas").insert({paciente_id:pacienteId,nome:novo.nome.trim(),codigo:novo.codigo||null,objetivo:novo.objetivo||null,bloco:novo.bloco||null,observacoes:novo.observacoes||null,frequencia_semanal:Number(novo.frequencia||3),ordem:treinos.length+1,status:"ativo"});setSaving(false);if(r.error)return alert(r.error.message);setNovo({nome:"",codigo:"",objetivo:"",bloco:"",observacoes:"",frequencia:"3"});setShowNew(false);await refreshCore()}
 async function salvarTreino(t:Treino,patch:Partial<Treino>){const r=await sb.from("treino_programas").update(patch).eq("id",t.id);if(r.error)return alert("Não foi possível salvar.");setTreinos(p=>p.map(x=>x.id===t.id?{...x,...patch}:x));setTodosTreinos(p=>p.map(x=>x.id===t.id?{...x,...patch}:x))}
 async function duplicar(t:Treino,destino=t.paciente_id,nome=`${t.nome} · Cópia`){setSaving(true);const n=await sb.from("treino_programas").insert({paciente_id:destino,nome,codigo:t.codigo,objetivo:t.objetivo,bloco:t.bloco,observacoes:t.observacoes,frequencia_semanal:t.frequencia_semanal,template_id:t.template_id,ordem:(todosTreinos.filter(x=>x.paciente_id===destino).length)+1,status:"ativo"}).select("id").single();if(n.error||!n.data){setSaving(false);return alert("Não foi possível copiar o treino.")}let lista:Exercicio[]=[];if(exercicios[t.id])lista=exercicios[t.id];else{const r=await sb.from("treino_exercicios").select("*").eq("treino_id",t.id).order("bloco_ordem").order("ordem");lista=(r.data??[]) as Exercicio[]}
  if(lista.length)await sb.from("treino_exercicios").insert(lista.map((e,i)=>({treino_id:n.data.id,bloco_ordem:e.bloco_ordem||1,bloco_nome:e.bloco_nome||"Principal",ordem:e.ordem||i+1,nome:e.nome,series:e.series,repeticoes:e.repeticoes,rir:e.rir,rpe:e.rpe,descanso_seg:e.descanso_seg,carga_inicial:e.carga_inicial,video_url:e.video_url,observacoes:e.observacoes,exercicio_biblioteca_id:e.exercicio_biblioteca_id})));
  setSaving(false);await refreshCore();return n.data.id as string}
 function formEx(id:string){return novoEx[id]??blankEx}function patchEx(id:string,p:Partial<typeof blankEx>){setNovoEx(s=>({...s,[id]:{...formEx(id),...p}}))}
 async function adicionarEx(tid:string){const f=formEx(tid);if(!f.nome.trim())return;setSaving(true);const r=await sb.from("treino_exercicios").insert({treino_id:tid,bloco_ordem:1,bloco_nome:"Principal",ordem:(exercicios[tid]?.length??0)+1,nome:f.nome.trim(),series:Number(f.series||1),repeticoes:f.repeticoes||null,rir:f.rir||null,descanso_seg:f.descanso?Number(f.descanso):null,video_url:f.video||null,observacoes:f.obs||null});setSaving(false);if(r.error)return alert(r.error.message);setNovoEx(s=>({...s,[tid]:blankEx}));await carregarTreinos(pacienteId)}
 async function salvarEx(e:Exercicio,patch:Partial<Exercicio>){const r=await sb.from("treino_exercicios").update(patch).eq("id",e.id);if(r.error)return alert("Não foi possível salvar o exercício.");setExercicios(s=>({...s,[e.treino_id]:(s[e.treino_id]??[]).map(x=>x.id===e.id?{...x,...patch}:x)}))}
 async function removerEx(e:Exercicio){if(!confirm(`Remover ${e.nome}?`))return;const r=await sb.from("treino_exercicios").delete().eq("id",e.id);if(r.error)return alert("Não foi possível remover.");setExercicios(s=>({...s,[e.treino_id]:(s[e.treino_id]??[]).filter(x=>x.id!==e.id)}))}
 async function alternarLiberacao(){const paciente=pacientes.find(p=>p.id===pacienteId);if(!paciente||!ativos.length)return;const liberar=!paciente.treino_liberado;if(!liberar&&!confirm("Recolher o treino da área do paciente? A prescrição será mantida no Admin."))return;setSaving(true);const r=await sb.from("pacientes").update({treino_liberado:liberar}).eq("id",paciente.id);setSaving(false);if(r.error)return alert("Não foi possível alterar a liberação do treino.");setPacientes(lista=>lista.map(p=>p.id===paciente.id?{...p,treino_liberado:liberar}:p))}
 async function salvarFrequenciaPaciente(value:number){if(!pacienteId)return;const r=await sb.from("pacientes").update({treino_frequencia_semanal:value}).eq("id",pacienteId);if(r.error)return alert("Não foi possível salvar a frequência.");setPacientes(p=>p.map(x=>x.id===pacienteId?{...x,treino_frequencia_semanal:value}:x))}

 async function salvarNaBiblioteca(t:Treino){
  const lista=exercicios[t.id]??[];if(!lista.length)return alert("Adicione pelo menos um exercício antes de salvar na biblioteca.");
  if(!confirm(`Salvar “${t.nome}” como modelo reutilizável na biblioteca?`))return;setSaving(true);
  const freq=t.frequencia_semanal||pacienteSelecionado?.treino_frequencia_semanal||3;
  const q=await sb.from("treino_templates").insert({nome:t.nome,descricao:t.observacoes,objetivo:t.objetivo,categoria:"Treino salvo",frequencia_semanal:freq,bloco:t.bloco,criado_de_treino_id:t.id}).select("*").single();
  if(q.error||!q.data){setSaving(false);return alert(q.error?.message||"Não foi possível salvar o modelo.")}
  const rows=lista.map((e,i)=>({template_id:q.data.id,exercicio_biblioteca_id:e.exercicio_biblioteca_id,bloco_ordem:e.bloco_ordem||1,bloco_nome:e.bloco_nome||"Principal",ordem:e.ordem||i+1,nome:e.nome,series:e.series,repeticoes:e.repeticoes,rir:e.rir,rpe:e.rpe,descanso_seg:e.descanso_seg,carga_inicial:e.carga_inicial,video_url:e.video_url,observacoes:e.observacoes}));
  const ins=await sb.from("treino_template_exercicios").insert(rows);setSaving(false);if(ins.error)return alert("O modelo foi criado, mas houve erro ao copiar os exercícios.");await bootstrap();alert("Treino salvo na biblioteca.")
 }

 async function aplicarTemplate(tpl:Template,destino=pacienteId){
  if(!destino)return alert("Selecione um paciente para receber o treino.");setSaving(true);
  const count=todosTreinos.filter(x=>x.paciente_id===destino).length;
  const r=await sb.from("treino_programas").insert({paciente_id:destino,nome:tpl.nome,objetivo:tpl.objetivo,bloco:tpl.bloco,observacoes:tpl.descricao,frequencia_semanal:tpl.frequencia_semanal,template_id:tpl.id,ordem:count+1,status:"ativo"}).select("id").single();
  if(r.error||!r.data){setSaving(false);return alert(r.error?.message||"Não foi possível aplicar o modelo.")}
  const lista=templateEx[tpl.id]??[];if(lista.length){const ins=await sb.from("treino_exercicios").insert(lista.map((e,i)=>({treino_id:r.data.id,exercicio_biblioteca_id:e.exercicio_biblioteca_id,bloco_ordem:e.bloco_ordem||1,bloco_nome:e.bloco_nome||"Principal",ordem:e.ordem||i+1,nome:e.nome,series:e.series,repeticoes:e.repeticoes,rir:e.rir,rpe:e.rpe,descanso_seg:e.descanso_seg,carga_inicial:e.carga_inicial,video_url:e.video_url,observacoes:e.observacoes})));if(ins.error){setSaving(false);return alert("O treino foi criado, mas houve erro ao copiar os exercícios.")}}
  setSaving(false);await refreshCore();setPacienteId(destino);setView("prescricao");alert("Treino adicionado ao paciente. O modelo original permaneceu intacto.")
 }
 async function arquivarTemplate(tpl:Template){if(!confirm(`Arquivar “${tpl.nome}” da biblioteca?`))return;const r=await sb.from("treino_templates").update({ativo:false}).eq("id",tpl.id);if(r.error)return alert("Não foi possível arquivar.");setTemplates(p=>p.filter(x=>x.id!==tpl.id))}
 async function copiarDeOutroPaciente(){const origem=todosTreinos.find(t=>t.id===copySourceWorkout);if(!origem||!pacienteId)return;await duplicar(origem,pacienteId,origem.nome);setCopySourceWorkout("");setCopySourcePatient("")}

 const ativos=treinos.filter(t=>t.status!=="arquivado");
 const pacienteSelecionado=pacientes.find(p=>p.id===pacienteId);
 const sourceWorkouts=todosTreinos.filter(t=>t.paciente_id===copySourcePatient&&t.status!=="arquivado");
 const objetivos=Array.from(new Set(templates.map(t=>t.objetivo).filter(Boolean))) as string[];
 const niveis=Array.from(new Set(templates.map(t=>t.nivel).filter(Boolean))) as string[];
 const filteredTemplates=templates.filter(t=>{const q=buscaTemplate.toLowerCase();return(!q||`${t.nome} ${t.objetivo??""} ${t.categoria??""} ${t.enfase??""}`.toLowerCase().includes(q))&&(!filtroObjetivo||t.objetivo===filtroObjetivo)&&(!filtroNivel||t.nivel===filtroNivel)});

 const analytics=useMemo<AnalyticsRow[]>(()=>{
  const now=new Date(),cut7=new Date(now.getTime()-7*86400000),cut14=new Date(now.getTime()-14*86400000),cut28=new Date(now.getTime()-28*86400000),prev14=new Date(now.getTime()-28*86400000);
  return pacientes.filter(p=>p.treino_liberado||todosTreinos.some(t=>t.paciente_id===p.id&&t.status!=="arquivado")).map(p=>{
   const pt=todosTreinos.filter(t=>t.paciente_id===p.id&&t.status!=="arquivado");const freq=Math.max(1,p.treino_frequencia_semanal||pt.find(t=>t.frequencia_semanal)?.frequencia_semanal||3);
   const pe=execucoes.filter(e=>e.paciente_id===p.id&&e.concluido);const d=(e:Execucao)=>new Date(e.finalizado_em||e.iniciado_em);
   const semana=pe.filter(e=>d(e)>=cut7).length,ultimos28=pe.filter(e=>d(e)>=cut28).length;const adesao=Math.min(100,Math.round(ultimos28/Math.max(1,freq*4)*100));
   const recent14=pe.filter(e=>d(e)>=cut14).length,older14=pe.filter(e=>d(e)>=prev14&&d(e)<cut14).length;const tendencia=recent14-older14;
   const ultimo=pe[0]?.finalizado_em||pe[0]?.iniciado_em||null;const diasSemTreino=ultimo?daysBetween(now,new Date(ultimo)):null;
   const prog=progressos.find(x=>x.paciente_id===p.id);const sessions=Object.values(prog?.dados?.sessions||{}) as any[];const sessaoAberta=sessions.some(s=>s?.started===true);
   let status:AnalyticsRow["status"]="Sem registro";if(ultimo&&diasSemTreino!=null&&diasSemTreino>=7)status="Inativo";else if(ultimo&&adesao>=80)status="Alta aderência";else if(ultimo&&adesao>=60)status="Atenção";else if(ultimo)status="Risco";
   return{paciente:p,frequencia:freq,semana,ultimos28,adesao,ultimo,diasSemTreino,tendencia,sessaoAberta,status};
  }).sort((a,b)=>{const rank={"Inativo":0,"Risco":1,"Sem registro":2,"Atenção":3,"Alta aderência":4};return rank[a.status]-rank[b.status]||a.adesao-b.adesao});
 },[pacientes,todosTreinos,execucoes,progressos]);
 const alerts=analytics.filter(a=>a.status==="Inativo"||a.status==="Risco"||a.status==="Sem registro");
 const avgAdherence=analytics.length?Math.round(analytics.reduce((s,a)=>s+a.adesao,0)/analytics.length):0;
 const totalWeek=analytics.reduce((s,a)=>s+a.semana,0);
 const activeRate=analytics.length?Math.round(analytics.filter(a=>a.status!=="Inativo"&&a.status!=="Sem registro").length/analytics.length*100):0;

 function exportCsv(){const rows=[["Paciente","Meta semanal","Treinos 7 dias","Treinos 28 dias","Aderência","Último treino","Dias sem treino","Tendência 14d","Status"],...analytics.map(a=>[a.paciente.nome||a.paciente.email||"Paciente",a.frequencia,a.semana,a.ultimos28,`${a.adesao}%`,a.ultimo?fmtDate(a.ultimo):"",a.diasSemTreino??"",a.tendencia,a.status])];const blob=new Blob(["\ufeff"+rows.map(r=>r.map(csvCell).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const el=document.createElement("a");el.href=url;el.download=`frequencia-treinos-${new Date().toISOString().slice(0,10)}.csv`;el.click();URL.revokeObjectURL(url)}

 const nav=<div className="mb-6 flex flex-wrap gap-2">
  <Button variant={view==="prescricao"?undefined:"outline"} onClick={()=>setView("prescricao")}><Dumbbell className="size-4"/> Prescrição</Button>
  <Button variant={view==="biblioteca"?undefined:"outline"} onClick={()=>setView("biblioteca")}><Library className="size-4"/> Biblioteca de treinos</Button>
  <Button variant={view==="engajamento"?undefined:"outline"} onClick={()=>setView("engajamento")}><Activity className="size-4"/> Frequência e retenção {alerts.length>0&&<span className="rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-700">{alerts.length}</span>}</Button>
 </div>;

 if(loading)return <div><PageHeader title="Treinos" description="Prescrição, biblioteca, frequência e retenção."/><Card><CardContent className="py-12 text-center text-sm text-muted">Carregando...</CardContent></Card></div>;

 return <div><PageHeader title="Treinos" description="Prescrição, biblioteca reutilizável e acompanhamento de aderência." actions={view==="prescricao"?<Button onClick={()=>setShowNew(v=>!v)}><Plus className="size-4"/> Novo treino</Button>:view==="engajamento"?<Button variant="outline" onClick={exportCsv}><Download className="size-4"/> Exportar relatório</Button>:undefined}/>{nav}

 {view==="prescricao"&&<>
  <Card className="mb-5"><CardContent className="pt-6"><div className="grid gap-4 md:grid-cols-[1fr_220px]"><div><Label>Paciente</Label><Select value={pacienteId} onChange={e=>setPacienteId(e.target.value)}><option value="">Selecione...</option>{pacientes.map(p=><option key={p.id} value={p.id}>{p.nome??p.email??"Paciente"}</option>)}</Select></div><div><Label>Meta de frequência semanal</Label><Select value={pacienteSelecionado?.treino_frequencia_semanal||3} onChange={e=>void salvarFrequenciaPaciente(Number(e.target.value))}>{freqOptions.map(n=><option key={n} value={n}>{n}x por semana</option>)}</Select></div></div><p className="mt-2 text-xs text-muted">{ativos.length} treino(s) ativo(s){pacienteSelecionado?.treino_liberado?" · treino liberado na área do paciente":""}</p></CardContent></Card>

  <Card className="mb-5"><CardContent className="pt-6"><div className="mb-3 flex items-center gap-2"><Copy className="size-4 text-brand-dark"/><h2 className="font-bold">Copiar treino de outro paciente</h2></div><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><Select value={copySourcePatient} onChange={e=>{setCopySourcePatient(e.target.value);setCopySourceWorkout("")}}><option value="">Paciente de origem...</option>{pacientes.filter(p=>p.id!==pacienteId).map(p=><option key={p.id} value={p.id}>{p.nome??p.email}</option>)}</Select><Select value={copySourceWorkout} onChange={e=>setCopySourceWorkout(e.target.value)}><option value="">Treino...</option>{sourceWorkouts.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</Select><Button variant="outline" disabled={saving||!copySourceWorkout||!pacienteId} onClick={()=>void copiarDeOutroPaciente()}>Copiar para paciente</Button></div></CardContent></Card>

  {showNew&&<Card className="mb-5"><CardContent className="pt-6"><h2 className="mb-4 font-bold">Novo treino do zero</h2><div className="grid gap-3 md:grid-cols-2"><div><Label>Nome *</Label><Input value={novo.nome} onChange={e=>setNovo({...novo,nome:e.target.value})} placeholder="Treino A · Inferiores"/></div><div><Label>Código</Label><Input value={novo.codigo} onChange={e=>setNovo({...novo,codigo:e.target.value})}/></div><div><Label>Objetivo</Label><Input value={novo.objetivo} onChange={e=>setNovo({...novo,objetivo:e.target.value})}/></div><div><Label>Bloco</Label><Input value={novo.bloco} onChange={e=>setNovo({...novo,bloco:e.target.value})}/></div><div><Label>Frequência semanal</Label><Select value={novo.frequencia} onChange={e=>setNovo({...novo,frequencia:e.target.value})}>{freqOptions.map(n=><option key={n} value={n}>{n}x/semana</option>)}</Select></div></div><div className="mt-3"><Label>Observações</Label><Textarea value={novo.observacoes} onChange={e=>setNovo({...novo,observacoes:e.target.value})}/></div><div className="mt-4 flex justify-end"><Button disabled={saving||!novo.nome.trim()} onClick={()=>void criarTreino()}>{saving?"Salvando...":"Criar treino"}</Button></div></CardContent></Card>}

  <div className="space-y-4">{ativos.map(t=><Card key={t.id}><CardContent className="pt-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 flex-1 items-center gap-2"><Dumbbell className="size-5 shrink-0 text-brand-dark"/><Input className="max-w-xl font-bold" value={t.nome} onChange={e=>setTreinos(s=>s.map(x=>x.id===t.id?{...x,nome:e.target.value}:x))} onBlur={e=>void salvarTreino(t,{nome:e.target.value})}/></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void salvarNaBiblioteca(t)}><Library className="size-4"/> Salvar na biblioteca</Button><Button variant="outline" onClick={()=>void duplicar(t)}><Copy className="size-4"/> Duplicar</Button><Button variant="outline" onClick={()=>void salvarTreino(t,{status:"arquivado"})}>Arquivar</Button></div></div><div className="mt-3 grid gap-3 md:grid-cols-[1fr_180px]"><p className="text-sm text-muted">{t.codigo?`${t.codigo} · `:""}{t.objetivo||"Sem objetivo descrito"}{t.bloco?` · ${t.bloco}`:""}</p><Select value={t.frequencia_semanal||3} onChange={e=>void salvarTreino(t,{frequencia_semanal:Number(e.target.value)})}>{freqOptions.map(n=><option key={n} value={n}>{n}x/semana</option>)}</Select></div>
   <div className="mt-5 space-y-3">{(exercicios[t.id]??[]).map((e,i)=><div key={e.id} className="rounded-xl border border-border bg-bg-alt p-4"><div className="mb-3 flex justify-between gap-2"><strong>{i+1}. {e.nome}</strong><button onClick={()=>void removerEx(e)} className="text-muted hover:text-red-600"><Trash2 className="size-4"/></button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><Label>Exercício</Label><Input value={e.nome} onChange={v=>setExercicios(s=>({...s,[t.id]:(s[t.id]??[]).map(x=>x.id===e.id?{...x,nome:v.target.value}:x)}))} onBlur={v=>void salvarEx(e,{nome:v.target.value})}/></div><div><Label>Séries</Label><Input type="number" defaultValue={e.series} onBlur={v=>void salvarEx(e,{series:Number(v.target.value)})}/></div><div><Label>Repetições</Label><Input defaultValue={e.repeticoes??""} onBlur={v=>void salvarEx(e,{repeticoes:v.target.value||null})}/></div><div><Label>RIR</Label><Input defaultValue={e.rir??""} onBlur={v=>void salvarEx(e,{rir:v.target.value||null})}/></div></div><div className="mt-3 grid gap-3 lg:grid-cols-3"><div><Label>Descanso (s)</Label><Input type="number" defaultValue={e.descanso_seg??""} onBlur={v=>void salvarEx(e,{descanso_seg:v.target.value?Number(v.target.value):null})}/></div><div><Label>Vídeo</Label><Input defaultValue={e.video_url??""} onBlur={v=>void salvarEx(e,{video_url:v.target.value||null})}/></div><div><Label>Orientações</Label><Input defaultValue={e.observacoes??""} onBlur={v=>void salvarEx(e,{observacoes:v.target.value||null})}/></div></div></div>)}</div>
   <div className="mt-4 rounded-xl border border-dashed border-border p-4"><p className="mb-3 text-sm font-semibold">Adicionar exercício</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><div className="lg:col-span-2"><Label>Exercício *</Label><Input value={formEx(t.id).nome} onChange={e=>patchEx(t.id,{nome:e.target.value})}/></div><div><Label>Séries</Label><Input type="number" value={formEx(t.id).series} onChange={e=>patchEx(t.id,{series:e.target.value})}/></div><div><Label>Repetições</Label><Input value={formEx(t.id).repeticoes} onChange={e=>patchEx(t.id,{repeticoes:e.target.value})}/></div><div><Label>RIR</Label><Input value={formEx(t.id).rir} onChange={e=>patchEx(t.id,{rir:e.target.value})}/></div><div><Label>Descanso</Label><Input type="number" value={formEx(t.id).descanso} onChange={e=>patchEx(t.id,{descanso:e.target.value})}/></div></div><div className="mt-3 grid gap-3 lg:grid-cols-2"><Input placeholder="URL do vídeo" value={formEx(t.id).video} onChange={e=>patchEx(t.id,{video:e.target.value})}/><Input placeholder="Orientações" value={formEx(t.id).obs} onChange={e=>patchEx(t.id,{obs:e.target.value})}/></div><div className="mt-3 flex justify-end"><Button disabled={saving||!formEx(t.id).nome.trim()} onClick={()=>void adicionarEx(t.id)}><Plus className="size-4"/> Adicionar exercício</Button></div></div>
  </CardContent></Card>)}{!ativos.length&&pacienteId&&<Card><CardContent className="py-12 text-center text-sm text-muted">Nenhum treino ativo para este paciente.</CardContent></Card>}</div>
  {pacienteId&&ativos.length>0&&<Card className="mt-5"><CardContent className="flex flex-col gap-4 pt-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-ink">Disponibilidade para o paciente</h2><p className="mt-1 text-sm text-muted">{pacienteSelecionado?.treino_liberado?"O treino está visível na Área do Paciente.":"Revise a prescrição e libere quando estiver pronta."}</p></div><Button variant={pacienteSelecionado?.treino_liberado?"outline":undefined} disabled={saving} onClick={()=>void alternarLiberacao()}>{pacienteSelecionado?.treino_liberado?<><EyeOff className="size-4"/> Recolher Treino</>:<><Eye className="size-4"/> Liberar Treino</>}</Button></CardContent></Card>}
 </>}

 {view==="biblioteca"&&<>
  <Card className="mb-5"><CardContent className="pt-6"><div className="grid gap-3 lg:grid-cols-[1fr_220px_220px_260px]"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted"/><Input className="pl-9" placeholder="Buscar por nome, objetivo ou ênfase..." value={buscaTemplate} onChange={e=>setBuscaTemplate(e.target.value)}/></div><Select value={filtroObjetivo} onChange={e=>setFiltroObjetivo(e.target.value)}><option value="">Todos os objetivos</option>{objetivos.map(x=><option key={x}>{x}</option>)}</Select><Select value={filtroNivel} onChange={e=>setFiltroNivel(e.target.value)}><option value="">Todos os níveis</option>{niveis.map(x=><option key={x}>{x}</option>)}</Select><Select value={pacienteId} onChange={e=>setPacienteId(e.target.value)}><option value="">Paciente para receber...</option>{pacientes.map(p=><option key={p.id} value={p.id}>{p.nome??p.email}</option>)}</Select></div></CardContent></Card>
  <div className="grid gap-4 xl:grid-cols-2">{filteredTemplates.map(t=><Card key={t.id}><CardContent className="pt-6"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2"><Library className="size-5 text-brand-dark"/><h2 className="text-lg font-bold">{t.nome}</h2></div><p className="text-sm text-muted">{t.objetivo||"Objetivo não informado"}{t.bloco?` · ${t.bloco}`:""}</p></div><span className="rounded-full bg-bg-alt px-3 py-1 text-xs font-semibold">{t.frequencia_semanal}x/sem</span></div><div className="mt-4 flex flex-wrap gap-2 text-xs text-muted">{t.categoria&&<span className="rounded-full border px-2 py-1">{t.categoria}</span>}{t.nivel&&<span className="rounded-full border px-2 py-1">{t.nivel}</span>}{t.enfase&&<span className="rounded-full border px-2 py-1">Ênfase: {t.enfase}</span>}{t.duracao_min&&<span className="rounded-full border px-2 py-1">{t.duracao_min} min</span>}<span className="rounded-full border px-2 py-1">{templateEx[t.id]?.length??0} exercícios</span></div>{t.descricao&&<p className="mt-4 text-sm text-muted">{t.descricao}</p>}<div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={()=>void arquivarTemplate(t)}>Arquivar</Button><Button disabled={saving||!pacienteId} onClick={()=>void aplicarTemplate(t)}><Plus className="size-4"/> Adicionar ao paciente</Button></div></CardContent></Card>)}{!filteredTemplates.length&&<Card><CardContent className="py-12 text-center text-sm text-muted">Nenhum treino encontrado na biblioteca. Em Prescrição, use “Salvar na biblioteca” em qualquer treino já montado.</CardContent></Card>}</div>
 </>}

 {view==="engajamento"&&<>
  <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><CardContent className="pt-6"><p className="text-xs font-semibold uppercase tracking-wide text-muted">Aderência média · 28 dias</p><p className="mt-2 text-3xl font-black">{avgAdherence}%</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-bg-alt"><div className="h-full bg-brand-dark" style={{width:`${avgAdherence}%`}}/></div></CardContent></Card><Card><CardContent className="pt-6"><p className="text-xs font-semibold uppercase tracking-wide text-muted">Treinos · últimos 7 dias</p><p className="mt-2 text-3xl font-black">{totalWeek}</p><p className="mt-2 text-sm text-muted">somando todos os pacientes monitorados</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-xs font-semibold uppercase tracking-wide text-muted">Pacientes ativos</p><p className="mt-2 text-3xl font-black">{activeRate}%</p><p className="mt-2 text-sm text-muted">com registro recente de treino</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-xs font-semibold uppercase tracking-wide text-muted">Precisam de atenção</p><p className="mt-2 text-3xl font-black text-red-600">{alerts.length}</p><p className="mt-2 text-sm text-muted">risco, inativos ou sem registro</p></CardContent></Card></div>

  {alerts.length>0&&<Card className="mb-5 border-red-200"><CardContent className="pt-6"><div className="mb-4 flex items-center gap-2"><AlertTriangle className="size-5 text-red-600"/><h2 className="font-bold">Pacientes que precisam de atenção</h2></div><div className="grid gap-3 lg:grid-cols-2">{alerts.slice(0,8).map(a=><button key={a.paciente.id} onClick={()=>{setPacienteId(a.paciente.id);setView("prescricao")}} className="flex items-center justify-between gap-3 rounded-xl border border-border p-4 text-left hover:bg-bg-alt"><div><p className="font-semibold">{a.paciente.nome??a.paciente.email}</p><p className="mt-1 text-xs text-muted">{a.status==="Sem registro"?"Ainda não concluiu nenhum treino":`${a.adesao}% de aderência · ${a.diasSemTreino??0} dia(s) sem treinar`}{a.sessaoAberta?" · sessão iniciada e ainda não concluída":""}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${a.status==="Inativo"?"bg-red-100 text-red-700":a.status==="Risco"?"bg-orange-100 text-orange-700":"bg-slate-100 text-slate-700"}`}>{a.status}</span></button>)}</div></CardContent></Card>}

  <Card><CardContent className="pt-6"><div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><Users className="size-5 text-brand-dark"/><h2 className="font-bold">Relatório de frequência</h2></div><p className="mt-1 text-sm text-muted">A aderência compara sessões concluídas nos últimos 28 dias com a meta semanal definida para cada paciente.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-muted"><th className="px-3 py-3">Paciente</th><th className="px-3 py-3">Meta</th><th className="px-3 py-3">7 dias</th><th className="px-3 py-3">28 dias</th><th className="px-3 py-3">Aderência</th><th className="px-3 py-3">Último treino</th><th className="px-3 py-3">Tendência</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{analytics.map(a=><tr key={a.paciente.id} className="border-b last:border-0"><td className="px-3 py-4"><button onClick={()=>{setPacienteId(a.paciente.id);setView("prescricao")}} className="font-semibold hover:underline">{a.paciente.nome??a.paciente.email}</button>{a.sessaoAberta&&<div className="mt-1 text-xs text-orange-600">Sessão em andamento/não concluída</div>}</td><td className="px-3 py-4">{a.frequencia}x/sem</td><td className="px-3 py-4">{a.semana}</td><td className="px-3 py-4">{a.ultimos28}</td><td className="px-3 py-4"><div className="flex items-center gap-2"><div className="h-2 w-20 overflow-hidden rounded-full bg-bg-alt"><div className="h-full bg-brand-dark" style={{width:`${a.adesao}%`}}/></div><strong>{a.adesao}%</strong></div></td><td className="px-3 py-4">{fmtDate(a.ultimo)}{a.diasSemTreino!=null&&<div className="text-xs text-muted">há {a.diasSemTreino} dia(s)</div>}</td><td className={`px-3 py-4 font-semibold ${a.tendencia<0?"text-red-600":a.tendencia>0?"text-green-700":"text-muted"}`}>{a.tendencia>0?`+${a.tendencia}`:a.tendencia} treino(s)</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${a.status==="Alta aderência"?"bg-green-100 text-green-700":a.status==="Atenção"?"bg-yellow-100 text-yellow-700":a.status==="Inativo"?"bg-red-100 text-red-700":a.status==="Risco"?"bg-orange-100 text-orange-700":"bg-slate-100 text-slate-700"}`}>{a.status}</span></td></tr>)}</tbody></table></div>{!analytics.length&&<div className="py-12 text-center text-sm text-muted">Ainda não há pacientes com treino para monitorar.</div>}</CardContent></Card>

  <Card className="mt-5"><CardContent className="pt-6"><h2 className="font-bold">Como o sistema está lendo engajamento</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl bg-bg-alt p-4"><strong>Alta aderência</strong><p className="mt-1 text-sm text-muted">80% ou mais da meta nas últimas 4 semanas.</p></div><div className="rounded-xl bg-bg-alt p-4"><strong>Atenção</strong><p className="mt-1 text-sm text-muted">60–79% da meta; vale acompanhar antes de cair.</p></div><div className="rounded-xl bg-bg-alt p-4"><strong>Risco</strong><p className="mt-1 text-sm text-muted">Abaixo de 60% mesmo com treino recente.</p></div><div className="rounded-xl bg-bg-alt p-4"><strong>Inativo</strong><p className="mt-1 text-sm text-muted">7 dias ou mais sem concluir uma sessão.</p></div></div></CardContent></Card>
 </>}
 </div>
}
