"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CalendarClock, MessageCircle, Plus, Search, Trash2, UserPlus, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Card, CardContent } from "@/components/ui/Card";
import { Input, Label, Textarea } from "@/components/ui/Input";
import { Modal } from "@/components/ui/Modal";
import { PageHeader } from "@/components/ui/PageHeader";
import { Select } from "@/components/ui/Select";
import { useToast } from "@/contexts/ToastContext";
import { LEAD_STAGES, type LeadStageKey } from "@/lib/leads/stages";
import { createLeadAction, deleteLeadAction, updateLeadAction } from "@/services/leads.actions";
import type { Lead } from "@/services/leads.queries";
import { cn } from "@/utils/cn";

const colors: Record<string, string> = { slate: "bg-slate-100 text-slate-700", amber: "bg-amber-100 text-amber-800", sky: "bg-sky-100 text-sky-800", rose: "bg-rose-100 text-rose-800" };
const empty = { nome: "", telefone: "", email: "", origem: "", planoInteresse: "", observacoes: "", proximaAcaoEm: "", urgente: false, etapa: "01_lead_recebido" as LeadStageKey };

function whatsapp(value?: string | null) { const digits = (value ?? "").replace(/\D/g, ""); return digits ? `https://wa.me/${digits.startsWith("55") ? digits : `55${digits}`}` : null; }
function localDate(value?: string | null) { if (!value) return ""; const d = new Date(value); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export function LeadsClient({ initialLeads }: { initialLeads: Lead[] }) {
  const router = useRouter(); const { toast } = useToast();
  const [leads, setLeads] = useState(initialLeads); const [search, setSearch] = useState("");
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState<Lead | null>(null);
  const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false);
  useEffect(() => setLeads(initialLeads), [initialLeads]);
  const filtered = useMemo(() => leads.filter((l) => `${l.nome} ${l.telefone} ${l.email} ${l.origem}`.toLowerCase().includes(search.toLowerCase())), [leads, search]);

  function begin(lead?: Lead) { setSelected(lead ?? null); setForm(lead ? { nome: lead.nome, telefone: lead.telefone ?? "", email: lead.email ?? "", origem: lead.origem ?? "", planoInteresse: lead.plano_interesse ?? "", observacoes: lead.observacoes ?? "", proximaAcaoEm: localDate(lead.proxima_acao_em), urgente: lead.urgente, etapa: lead.etapa as LeadStageKey } : empty); setOpen(true); }
  async function save() { setSaving(true); const payload = { ...form, proximaAcaoEm: form.proximaAcaoEm ? new Date(form.proximaAcaoEm).toISOString() : null }; const result = selected ? await updateLeadAction(selected.id, payload) : await createLeadAction(payload); setSaving(false); if (!result.success) return toast({ kind: "error", title: "Não foi possível salvar", description: result.message }); toast({ kind: "success", title: result.message }); setOpen(false); router.refresh(); }
  async function move(lead: Lead, etapa: LeadStageKey) { const old = leads; setLeads((all) => all.map((item) => item.id === lead.id ? { ...item, etapa } : item)); const result = await updateLeadAction(lead.id, { etapa }); if (!result.success) { setLeads(old); toast({ kind: "error", title: result.message }); } else router.refresh(); }
  function drop(e: React.DragEvent, etapa: LeadStageKey) { e.preventDefault(); const lead = leads.find((l) => l.id === e.dataTransfer.getData("text/lead-id")); if (lead && lead.etapa !== etapa) void move(lead, etapa); }
  async function remove() { if (!selected || !confirm(`Excluir o lead ${selected.nome}?`)) return; const result = await deleteLeadAction(selected.id); if (result.success) { setOpen(false); router.refresh(); } else toast({ kind: "error", title: result.message }); }

  return <div>
    <PageHeader title="Leads" description="Organize os novos contatos desde a primeira conversa até o agendamento." actions={<Button onClick={() => begin()}><Plus className="size-4" /> Novo lead</Button>} />
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><Card><CardContent className="flex items-center gap-3 pt-6"><UsersRound className="size-5 text-brand-dark"/><div><p className="text-xl font-bold">{leads.length}</p><p className="text-xs text-muted">Leads ativos</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 pt-6"><CalendarClock className="size-5 text-warning"/><div><p className="text-xl font-bold">{leads.filter(l => l.proxima_acao_em).length}</p><p className="text-xs text-muted">Com próxima ação</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 pt-6"><AlertTriangle className="size-5 text-danger"/><div><p className="text-xl font-bold">{leads.filter(l => l.urgente).length}</p><p className="text-xs text-muted">Urgentes</p></div></CardContent></Card></div>
    <Card className="mb-5"><CardContent className="pt-6"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted"/><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por nome, telefone, e-mail ou origem..." className="pl-9"/></div></CardContent></Card>
    <div className="scrollbar-thin flex gap-4 overflow-x-auto pb-5">{LEAD_STAGES.map(stage => { const items = filtered.filter(l => l.etapa === stage.key); return <section key={stage.key} onDragOver={e => e.preventDefault()} onDrop={e => drop(e, stage.key)} className="w-[300px] shrink-0 rounded-xl bg-bg-alt p-3"><div className="mb-3 flex items-center justify-between"><span className={cn("rounded-full px-2.5 py-1 text-xs font-bold", colors[stage.color])}>{stage.label}</span><span className="rounded-full bg-surface px-2 py-0.5 text-xs font-bold text-muted">{items.length}</span></div><div className="space-y-3">{items.map(lead => <article key={lead.id} draggable onDragStart={e => e.dataTransfer.setData("text/lead-id", lead.id)} className="rounded-lg border border-border bg-surface p-4 shadow-card"><button onClick={() => begin(lead)} className="w-full text-left"><div className="flex justify-between gap-2"><h3 className="font-bold text-ink">{lead.nome}</h3>{lead.urgente && <AlertTriangle className="size-4 text-danger"/>}</div><p className="mt-1 text-xs text-muted">{lead.origem || "Origem não informada"}{lead.plano_interesse ? ` · ${lead.plano_interesse}` : ""}</p>{lead.proxima_acao_em && <p className="mt-3 text-xs font-semibold text-warning">Próxima ação: {new Date(lead.proxima_acao_em).toLocaleString("pt-BR", {day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</p>}</button><div className="mt-3 flex gap-2 border-t border-border pt-3"><Select value={lead.etapa} onChange={e => void move(lead, e.target.value as LeadStageKey)} className="py-1.5 text-xs">{LEAD_STAGES.map(s => <option key={s.key} value={s.key}>{s.label}</option>)}</Select>{whatsapp(lead.telefone) && <a href={whatsapp(lead.telefone)!} target="_blank" rel="noreferrer" className="rounded-md border border-border p-2 text-brand-dark"><MessageCircle className="size-4"/></a>}</div></article>)}{items.length === 0 && <div className="rounded-lg border border-dashed border-border px-4 py-8 text-center text-xs text-muted">Arraste um lead para esta etapa</div>}</div></section>; })}</div>
    <Modal open={open} onClose={() => setOpen(false)} title={selected ? "Editar lead" : "Novo lead"} description="Cadastre somente os dados comerciais disponíveis agora."><div className="space-y-4"><div><Label>Nome *</Label><Input value={form.nome} onChange={e => setForm({...form,nome:e.target.value})}/></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>WhatsApp</Label><Input value={form.telefone} onChange={e => setForm({...form,telefone:e.target.value})}/></div><div><Label>E-mail</Label><Input type="email" value={form.email} onChange={e => setForm({...form,email:e.target.value})}/></div><div><Label>Origem do lead</Label><Input value={form.origem} onChange={e => setForm({...form,origem:e.target.value})} placeholder="Instagram, indicação, Google..."/></div><div><Label>Plano de interesse</Label><Input value={form.planoInteresse} onChange={e => setForm({...form,planoInteresse:e.target.value})}/></div></div><div><Label>Etapa</Label><Select value={form.etapa} onChange={e => setForm({...form,etapa:e.target.value as LeadStageKey})}>{LEAD_STAGES.map(s => <option key={s.key} value={s.key}>{s.label}</option>)}</Select></div><div><Label>Próxima ação</Label><Input type="datetime-local" value={form.proximaAcaoEm} onChange={e => setForm({...form,proximaAcaoEm:e.target.value})}/></div><div><Label>Observações</Label><Textarea className="min-h-28" value={form.observacoes} onChange={e => setForm({...form,observacoes:e.target.value})}/></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.urgente} onChange={e => setForm({...form,urgente:e.target.checked})} className="size-4 accent-brand"/> Marcar como urgente</label><div className="flex flex-wrap justify-between gap-2">{selected ? <Button variant="ghost" onClick={() => void remove()} className="text-danger"><Trash2 className="size-4"/> Excluir</Button> : <span/>}<div className="flex gap-2"><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={() => void save()} disabled={saving || form.nome.trim().length < 2}>{saving ? "Salvando..." : "Salvar lead"}</Button></div></div>{selected && <div className="rounded-lg border border-dashed border-brand/40 bg-brand-light/40 p-4"><p className="text-sm font-bold text-ink">O lead agendou?</p><p className="mt-1 text-xs text-muted">Cadastre-o como paciente para gerar acesso, plano e prontuário. Depois, exclua este lead.</p><a href="/pacientes" className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-brand-dark"><UserPlus className="size-4"/> Ir para cadastro de pacientes</a></div>}</div></Modal>
  </div>;
}
