"use client";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { Check,ChevronLeft,ChevronRight,Copy,Plus,ReceiptText } from "lucide-react";
import { Button } from "@/components/ui/Button"; import { Card,CardContent } from "@/components/ui/Card"; import { Input,Label,Textarea } from "@/components/ui/Input"; import { Modal } from "@/components/ui/Modal"; import { PageHeader } from "@/components/ui/PageHeader"; import { Select } from "@/components/ui/Select";
import { createPagamentoAction,toggleNotaAction } from "@/services/pagamentos";
import { SERVICOS,type ServicoKey } from "@/lib/pagamentos/catalogo";
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
export function PagamentosClient({initialPagamentos,pacientes}:{initialPagamentos:any[];pacientes:any[]}){
 const router=useRouter(), now=new Date(); const [month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1)); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [copied,setCopied]=useState<string|null>(null); const [form,setForm]=useState({paciente_id:"",servico:"plano_essencial" as ServicoKey,valor:"",pago_em:new Date().toISOString().slice(0,10),forma_pagamento:"",observacoes:""});
 const rows=useMemo(()=>initialPagamentos.filter(p=>{const d=new Date(p.pago_em);return d.getFullYear()===month.getFullYear()&&d.getMonth()===month.getMonth()}),[initialPagamentos,month]); const total=rows.reduce((s,p)=>s+Number(p.valor),0); const title=month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});
 async function save(){setSaving(true);const r=await createPagamentoAction({...form,valor:Number(form.valor)});setSaving(false);if(r.success){setOpen(false);router.refresh()}else alert(r.message)}
 async function copyText(id:string,text:string){await navigator.clipboard.writeText(text);setCopied(id);setTimeout(()=>setCopied(null),1600)}
 function transactionText(p:any){const servico=SERVICOS[p.servico as ServicoKey]?.label??p.servico??"Serviço"; const data=p.pago_em?new Date(p.pago_em).toLocaleDateString("pt-BR"):""; return `Paciente: ${p.pacientes?.nome??"Paciente"}\nServiço: ${servico}\nValor: ${brl.format(Number(p.valor))}\nData do pagamento: ${data}${p.forma_pagamento?`\nForma de pagamento: ${p.forma_pagamento}`:""}\n\nDescrição da nota:\n${p.descricao_nota??""}${p.observacoes?`\n\nObservações:\n${p.observacoes}`:""}`}
 return <div><PageHeader title="Pagamentos" description="Controle mensal de recebimentos e descrições prontas para emissão de nota." actions={<Button onClick={()=>setOpen(true)}><Plus className="size-4"/> Novo pagamento</Button>}/>
 <div className="mb-5 flex items-center justify-between rounded-xl border border-border bg-surface p-3"><Button variant="ghost" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft className="size-4"/></Button><strong className="capitalize">{title}</strong><Button variant="ghost" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight className="size-4"/></Button></div>
 <div className="mb-5 grid gap-3 sm:grid-cols-4"><Card><CardContent className="pt-6"><p className="text-xs text-muted">Total recebido</p><p className="text-xl font-bold">{brl.format(total)}</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-xs text-muted">Pagamentos</p><p className="text-xl font-bold">{rows.length}</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-xs text-muted">Notas pendentes</p><p className="text-xl font-bold">{rows.filter(p=>!p.nota_emitida).length}</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-xs text-muted">Notas emitidas</p><p className="text-xl font-bold">{rows.filter(p=>p.nota_emitida).length}</p></CardContent></Card></div>
 <div className="space-y-3">{rows.map(p=><Card key={p.id}><CardContent className="pt-6"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><ReceiptText className="size-4 text-brand-dark"/><h3 className="font-bold">{p.pacientes?.nome??"Paciente"}</h3></div><p className="mt-1 text-sm font-semibold">{SERVICOS[p.servico as ServicoKey]?.label} · {brl.format(Number(p.valor))}</p><div className="mt-3 flex items-start gap-2 rounded-lg bg-bg-alt p-3"><p className="flex-1 text-sm text-muted">{p.descricao_nota}</p><button type="button" className="shrink-0 rounded-md p-1.5 text-muted transition hover:bg-surface hover:text-ink" title="Copiar descrição" onClick={()=>void copyText(`desc-${p.id}`,p.descricao_nota??"")}>{copied===`desc-${p.id}`?<Check className="size-4"/>:<Copy className="size-4"/>}</button></div><p className="mt-2 text-xs text-muted">Pagamento: {p.pago_em?new Date(p.pago_em).toLocaleDateString("pt-BR"):""}{p.forma_pagamento?` · ${p.forma_pagamento}`:""}</p></div><div className="flex shrink-0 flex-wrap gap-2"><Button variant="outline" onClick={()=>void copyText(`all-${p.id}`,transactionText(p))}>{copied===`all-${p.id}`?<Check className="size-4"/>:<Copy className="size-4"/>}{copied===`all-${p.id}`?" Copiado":" Copiar tudo"}</Button><Button variant={p.nota_emitida?"outline":"primary"} onClick={async()=>{await toggleNotaAction(p.id,!p.nota_emitida);router.refresh()}}>{p.nota_emitida?"Nota emitida":"Marcar nota emitida"}</Button></div></div></CardContent></Card>)}{!rows.length&&<Card><CardContent className="py-12 text-center text-sm text-muted">Nenhum pagamento registrado neste mês.</CardContent></Card>}</div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Novo pagamento" description="Registre o recebimento; a descrição da nota será preenchida automaticamente."><div className="space-y-4"><div><Label>Paciente *</Label><Select value={form.paciente_id} onChange={e=>setForm({...form,paciente_id:e.target.value})}><option value="">Selecione...</option>{pacientes.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</Select></div><div><Label>Serviço *</Label><Select value={form.servico} onChange={e=>setForm({...form,servico:e.target.value as ServicoKey})}>{Object.entries(SERVICOS).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</Select></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Valor (R$) *</Label><Input type="number" step="0.01" value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})}/></div><div><Label>Data do pagamento *</Label><Input type="date" value={form.pago_em} onChange={e=>setForm({...form,pago_em:e.target.value})}/></div></div><div><Label>Forma de pagamento</Label><Input value={form.forma_pagamento} onChange={e=>setForm({...form,forma_pagamento:e.target.value})} placeholder="PIX, cartão, dinheiro..."/></div><div className="rounded-lg bg-bg-alt p-3 text-xs text-muted"><strong className="text-ink">Descrição da nota:</strong><br/>{SERVICOS[form.servico].descricao}</div><div><Label>Observações</Label><Textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={saving||!form.paciente_id||!form.valor} onClick={()=>void save()}>{saving?"Salvando...":"Salvar pagamento"}</Button></div></div></Modal></div>
}