-- Orientações premium por refeição-modelo da Biblioteca Clínica v1.
-- Aplicada em produção em 17/08/2026. Mantém substituições e demais observações já existentes nos planos.

with orientacoes(modelo, texto) as (values
('B01 Café tradicional', 'Para ganhar tempo pela manhã, deixe a proteína já pronta na geladeira e apenas aqueça na hora. Para os ovos, prefira fogo baixo e desligue antes de ressecar; isso melhora bastante a textura. A fruta pode ser deixada lavada e porcionada na noite anterior. Se a rotina apertar, monte tudo em versão sanduíche e leve para consumir depois.'),
('B02 Bowl proteico', 'Misture primeiro o iogurte com o whey até ficar homogêneo e só depois acrescente aveia e fruta. Para uma textura mais cremosa, deixe o bowl 10 a 15 minutos na geladeira antes de consumir; para uma versão mais fluida, use um pouco de água. Se precisar sair cedo, deixe os ingredientes secos separados e misture no pote somente na hora para não perder textura.'),
('B03 Cuscuz com proteína', 'Para o cuscuz ficar mais úmido, hidrate o flocão antes do preparo e evite cozinhar por tempo excessivo. Deixe o frango já desfiado e porcionado por 2 a 3 dias ou congele em pequenas porções. Uma solução prática é misturar a proteína ao cuscuz ainda quente, formando uma refeição única e fácil de transportar.'),
('B04 Iogurte, fruta e aveia', 'Deixe uma porção pronta em pote com tampa para facilitar a rotina. Se for consumir várias horas depois, leve a aveia separada e misture apenas na hora para manter a textura. A fruta pode ser trocada conforme disponibilidade, mantendo a quantidade indicada. Em dias corridos, essa refeição funciona bem como opção de levar na bolsa térmica.'),
('B05 Fruta, cottage e castanhas', 'Prefira montar a refeição em um único pote para facilitar o consumo fora de casa. Se o cottage ficar muito seco, misture com um pouco da própria fruta picada. As castanhas podem ser porcionadas previamente em pequenos potes ou saquinhos para evitar comer direto da embalagem e perder a referência da quantidade.'),
('B06 Mini sanduíche', 'Deixe o recheio proteico pronto e refrigerado por até alguns dias, porcionado para montagem rápida. Para o sanduíche não ficar seco, use tomate, folhas ou pepino e aqueça o pão rapidamente antes de montar. Se precisar levar, embrulhe em papel-alumínio ou papel-manteiga e transporte os vegetais mais úmidos separados para montar na hora.'),
('B07 Almoço brasileiro', 'Use o peso dos alimentos já prontos como referência. Uma boa estratégia é preparar arroz, feijão e proteína em maior quantidade e montar porções individuais para 2 a 3 dias. Congele o restante em porções prontas para os dias mais corridos. Para melhorar sabor sem depender de molhos prontos, varie alho, cebola, ervas, páprica, limão e pimenta. Acrescente o azeite somente depois do preparo, na quantidade indicada.'),
('B08 Almoço carne vermelha', 'Para a carne ficar mais macia, prefira cortes em tiras finas ou cubos pequenos e evite cozinhar por tempo excessivo. Refogue em panela bem quente e finalize com temperos, em vez de deixar muito tempo no fogo. Arroz, lentilha e carne podem ser preparados em lote e congelados em porções individuais para facilitar a semana.'),
('B09 Almoço peixe e tubérculo', 'Para o peixe não ressecar, asse ou grelhe por pouco tempo e retire assim que estiver cozido no centro. Limão, ervas, alho e páprica ajudam a variar o sabor sem precisar de molhos pesados. A batata pode ser cozida em maior quantidade e depois finalizada na air fryer ou frigideira na hora de comer para recuperar textura.'),
('B10 Sanduíche completo', 'Deixe o recheio proteico pronto para 2 a 3 dias e monte o sanduíche somente na hora de consumir. Para melhorar textura e saciedade, acrescente vegetais crocantes e use o abacate amassado como base do pão. Se for levar para o trabalho, mantenha a fruta separada e monte os ingredientes mais úmidos apenas perto do horário da refeição.'),
('B11 Bowl proteico da tarde', 'Misture o whey ao iogurte antes de acrescentar os demais ingredientes para evitar grumos. Se quiser uma versão mais refrescante, use a fruta gelada ou congelada em pedaços. Em dias muito corridos, deixe um kit pronto com whey e aveia já porcionados e acrescente apenas o iogurte e a fruta na hora.'),
('B12 Cuscuz e ovos', 'Hidrate o cuscuz alguns minutos antes de cozinhar para ele ficar mais macio. Prepare os ovos em fogo baixo, mexendo pouco, para manter cremosidade. Se precisar levar, cuscuz e ovos podem ser montados em um único pote e aquecidos rapidamente; a fruta fica melhor separada.'),
('B13 Jantar tradicional', 'Use o jantar como uma refeição simples de repetir e não como uma segunda oportunidade de cozinhar do zero. Aproveite preparações do almoço ou deixe porções congeladas para os dias mais cansativos. Aqueça somente a porção que será consumida e finalize os vegetais na hora para preservar textura. O azeite entra depois do preparo, na quantidade indicada.'),
('B14 Jantar sanduíche', 'Uma solução prática para noites corridas é deixar a carne pronta e porcionada e montar o sanduíche em poucos minutos. Aqueça a proteína separadamente e monte no pão apenas no final para evitar que fique úmido. Use tomate e folhas para trazer volume e frescor; o abacate pode ser amassado com limão e uma pitada de sal para funcionar como creme.'),
('B15 Jantar peixe e batata-doce', 'Asse a batata-doce em quantidade maior e guarde porções prontas; na hora de consumir, finalize na air fryer para recuperar a textura. O peixe deve ser preparado por pouco tempo para não ressecar. Se quiser variar o sabor, use combinações como limão e ervas, páprica e alho ou mostarda em pequena quantidade, sem alterar as porções do plano.')
)
update public.refeicao_modelo_opcoes o
set observacoes=orientacoes.texto
from public.refeicoes_modelo r, orientacoes
where o.refeicao_modelo_id=r.id
  and r.biblioteca='clinica_v1'
  and o.ordem=0
  and orientacoes.modelo=r.nome;
